language: java
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
dist: trusty
jdk:
  - oraclejdk8

git:
  clone: false

before_install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - git remote add uptream https://github.com/apache/jackrabbit-filevault.git
  - cd $TRAVIS_REPO_SLUG
  - git branch

install:
  - echo 'Merge Trunk into Master'
  - git merge trunk
#  - echo 'Merge Features into Master'
#  - git merge feature/enable-insecure-https-host
  
## Deploy packages to git
deploy:
  - provider: script
    script: mvn clean deploy -Dregistry=https://maven.pkg.github.com/aem-design -Dtoken=$GITHUB_TOKEN
    on:
      branch: master
