language: java
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
dist: trusty
jdk:
  - oraclejdk8

git:
  clone: false

before_install:
  - sudo apt-get install tree
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - pwd
  - git checkout master
  - git remote add uptream https://github.com/apache/jackrabbit-filevault.git
  #  - echo 'Merge Trunk into Master'
  #  - git merge trunk
  #  - echo 'Merge Features into Master'
  #  - git merge feature/enable-insecure-https-host
  - export MAVEN_OPTS="-Xmx2024M -Xss128M -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=2024M -XX:+CMSClassUnloadingEnabled"
  - mvn clean -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Drat.skip=true && echo "CLEAN DONE"
  - mvn package -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Drat.skip=true && echo "PACKAGE AND LOCAL INSTALL DONE"
  - echo 'display tree of ./parent/target folder'
  - tree -P "*.pom|*.jar|*.xml" ./parent/target
  - echo 'display tree of ./target folder'
  - tree -P "*.pom|*.jar|*.xml" ./target

install:
  - echo 'display tree of ./parent/target folder before mvn install'
  - tree -P "*.pom|*.jar|*.xml" ./parent/target
  - echo 'display tree of ./target folder before mvn install'
  - tree -P "*.pom|*.jar|*.xml" ./target
  - mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Drat.skip=true && echo "INSTALL DONE"
  - echo 'display tree of ./parent/target folder after mvn install'
  - tree -P "*.pom|*.jar|*.xml" ./parent/target
  - echo 'display tree of ./target folder after mvn install'
  - tree -P "*.pom|*.jar|*.xml" ./target

## Deploy packages to git
deploy:
  - provider: script
#    script: mvn -X deploy -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Drat.skip=true -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/$TRAVIS_REPO_SLUG --settings settings.xml && echo "DEPLPOY DONE"
    script: mvn -X deploy -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Drat.skip=true -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/aem-design --settings settings.xml && echo "DEPLPOY DONE"
    on:
      branch: master
#    script: mvn -X deploy -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Drat.skip=true -Dregistry=https://maven.pkg.github.com/aem-design -Dtoken=$GITHUB_TOKEN && echo "DEPLPOY DONE"
#    script: mvn -X deploy -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -Drat.skip=true -DrepositoryId=github -Durl=https://maven.pkg.github.com/aem-design --settings settings.xml && echo "DEPLPOY DONE"
