language: java
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
dist: trusty
jdk:
  - oraclejdk8

git:
  clone: false

before_install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout master
  - git remote add uptream https://github.com/apache/jackrabbit-filevault.git
  #  - echo 'Merge Trunk into Master'
  #  - git merge trunk
  #  - echo 'Merge Features into Master'
  #  - git merge feature/enable-insecure-https-host
  - export MAVEN_OPTS="-Xmx2024M -Xss128M -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=2024M -XX:+CMSClassUnloadingEnabled"
  - mvn clean -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true && echo "CLEAN DONE"
  - mvn package -DskipTests=true && echo "PACKAGE AND LOCAL INSTALL DONE"

install:
  - mvn install -DskipTests=true -Drat.skip=true && echo "INSTALL DONE"
  - sudo apt-get install tree
  - tree /home/travis/.m2/repository/org/apache/jackrabbit/vault
  - pwd
  - cat settings.xml

## Deploy packages to git
deploy:
  - provider: script
    script: mvn -X deploy -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/$TRAVIS_REPO_SLUG --settings settings.xml
    on:
      branch: master
#    script: mvn clean deploy -Dregistry=https://maven.pkg.github.com/aem-design -Dtoken=$GITHUB_TOKEN
#    script: mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/aem-design --settings settings.xml -DskipTests=true && echo "DEPLPOY DONE"
#    script: mvn deploy -DrepositoryId=github -Durl=https://maven.pkg.github.com/aem-design --settings settings.xml -DskipTests=true && echo "DEPLPOY DONE"
