language: java
sudo: false
cache:
  directories:
    - '$HOME/.m2/repository'
dist: trusty
jdk:
  - oraclejdk8

git:
  clone: false

before_install:
  - git clone https://github.com/$TRAVIS_REPO_SLUG.git $TRAVIS_REPO_SLUG
  - cd $TRAVIS_REPO_SLUG
  - git checkout master
  - git remote add uptream https://github.com/apache/jackrabbit-filevault.git
  #  - echo 'Merge Trunk into Master'
  #  - git merge trunk
  #  - echo 'Merge Features into Master'
  #  - git merge feature/enable-insecure-https-host
  - export MAVEN_OPTS="-Xmx2024M -Xss128M -XX:MetaspaceSize=512M -XX:MaxMetaspaceSize=2024M -XX:+CMSClassUnloadingEnabled"
  - mvn clean -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -Dmaven.source.skip=true -B -q && echo "CLEAN DONE"
  - mvn package -DskipTests=true -B -q && echo "PACKAGE AND LOCAL INSTALL DONE"

install:
  - mvn install -DskipTests=true -Drat.skip=true -B -q && echo "INSTALL DONE"

## Deploy packages to git
deploy:
  - provider: script
#    script: mvn deploy -DaltDeploymentRepository=github::default::https://maven.pkg.github.com/aem-design --settings settings.xml -DskipTests=true -q -B && echo "DEPLPOY DONE"
    script: mvn deploy -DrepositoryId=github -Durl=https://maven.pkg.github.com/aem-design --settings settings.xml -DskipTests=true -q -B && echo "DEPLPOY DONE"
    on:
      branch: master